### ISSUE TITLE
Main program running time is too long... 

### ISSUE THREAD

**Issue by zhuhu00** [facebookresearch/robust_cvd#17]
I try to run your code on google colab, but the running time for `main.py` is very long(more than 2 hours even using demo video), the program gets stuck in this position every time. Is this normal? I am not colab pro.
![image](https://user-images.githubusercontent.com/29742046/128624422-16b9aa37-a255-4dcc-a9dd-b4194dcb66f5.png)

**Comment by ionvision** [comment]
Hey, it's mainly due to that the homography computation takes quite some time. We will try to improve it in the next update.

<img width="538" alt="CleanShot 2021-08-09 at 12 06 38@2x" src="https://user-images.githubusercontent.com/2598169/128760476-5df7b615-2e42-48f8-a271-755fc7ee3a66.png">

https://robust-cvd.github.io/robust_cvd_supp.pdf

**Comment by zhuhu00** [comment]
I see. Thank you very much for your answer, and I look forward to your update.
