### ISSUE TITLE
Why images get downscaled?

### ISSUE THREAD

**Issue by semel1** [facebookresearch/robust_cvd#9]
Why all processed streams down scaled?
Is there is a way to process and obtain depth in the same  resolution as input source (without upscale processed images back to the original resolution)?

**Comment by jbhuang0604** [comment]
The images are downscaled because the pre-trained depth model (MiDaS-v2 in this case) operates only at a downscaled image resolution (with the long-side of the image of size 384). One could potentially upscale the estimated depth map from our method back to the original image resolution using some kind of super-resolution algorithms.
